### ISSUE TITLE
Odd handling of invalid option to Toml.decode/2

### ISSUE THREAD

**Issue by RichMorin** [bitwalker/toml-elixir#11]
When I called `Toml.decode/2` with the option `:atom` (rather than the intended `:atoms`), it returned an error with the reason `:function_clause`.  This seemed a bit inscrutable, so I tried using `Toml.Error.format_reason/1` to explicate it.  However, the result was unchanged: `:function_clause`.
Maybe this reason needs to be added to `Toml.Error.format_reason/1`?

**Comment by bitwalker** [comment]
Thanks for reporting! Looks like we were missing some validation around that option beyond pattern matching, I've pushed a fix in 0.5.2
