### ISSUE TITLE
Is the environment variable in distillery parsed at runtime?

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [bitwalker/toml-elixir#2]
Hello, in the documentation you show: `{Toml.Provider, [path: "${XDG_CONFIG_DIR}/myapp.toml", transforms: [...]]}`
Is that environment variable parsed at runtime or at compile time (well, "release" time)?

It makes a huge difference: if it's parsed during the release procedure, I cannot have the same app running in the same server with 2 different configs.

**Comment by bitwalker** [comment]
It is expanded when the provider is initialized, i.e. at runtime, not compile-time.
