### ISSUE TITLE
Not loading config provider

### ISSUE THREAD

**Issue by samuelebistoletti** [bitwalker/toml-elixir#23]
Hi,
I use Distillery 2.1 and set this for config provider:

`
  set config_providers: [
    {Toml.Provider, [path: "/full/path/config.toml"]}
  ]
`

When I start the application in production variables are not replaced with values in config.toml, I still got variable contents from config.exs. Before upgrade to Elixir 1.9 and Distillery 2.1 everything worked as expected.

Any suggestions? 
Thanks

**Comment by philipgiuliani** [comment]
We have the same problem after upgrading to Elixir 1.9 and Distillery 2.1.

**Comment by jeffweiss** [comment]
We also ran into this issue, tracked it down and provided a fix in #25.
