### ISSUE TITLE
TOML 1.0?

### ISSUE THREAD

**Issue by anthonator** [bitwalker/toml-elixir#32]
Is there any interest from @bitwalker or community to support TOML 1.0? I'd be happy to contribute however I can but want to make sure there's interest before starting.

**Comment by bitwalker** [comment]
Certainly! There weren't any major changes in the jump to 1.0, it being more of a backwards-compat commitment than anything, but there are some. Would love to make sure things are compliant!

**Comment by bitwalker** [comment]
I'm going to close this issue for now, since we've updated the docs to mention we're 1.0 compliant - if there are bugs in our compliance lets treat those as individual issues to be addressed (and PRs are always welcome).
