### ISSUE TITLE
Wrong spec for parse_file?

### ISSUE THREAD

**Issue by bortzmeyer** [bitwalker/toml-elixir#33]
The [documentation](https://hexdocs.pm/toml_elixir/TomlElixir.html#parse_file/2) says that `parse_file` can return `{:ok, …}` or  `{:error, [Exception.t]}`. But, apparently,  `parse_file` can also return  `{:error, atom}`:

```
iex(2)> TomlElixir.parse_file("doesnotexist")
{:error, :enoent}
```
Because of this erroneous spec, Dialyzer complains when I use TOML:

```
lib/drink/toml.ex:10:pattern_match
The pattern can never match the type.

Pattern:
{:error, :enoent}

Type:
{:error, %{:__exception__ => true, :__struct__ => atom(), atom() => _}}

________________________________________________________________________________
```

As seen above `parse_file`  *can* return ` {:error, :enoent}`.

**Comment by bitwalker** [comment]
This is the `:toml` library, not `:toml_elixir`
